name: ci
'on':
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: BijuBuild
        run: dotnet build --no-restore
      - name: BijuTest2
        run: >-
          dotnet test /home/runner/work/MyTestRepo/MyTestRepo/ConsoleApp1.sln
          --no-restore  --no-restore --collect:"XPlat Code Coverage" --logger
          trx  --results-directory ./test-results
  build_main2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
      - name: BijuBuild
        run: dotnet build --no-restore
      - name: BijuTest2
        run: >-
          dotnet test /home/runner/work/MyTestRepo/MyTestRepo/ConsoleApp1.sln
          --no-restore  --no-restore --collect:"XPlat Code Coverage" --logger
          trx  --results-directory ./test-results
